name: Extension Release

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/extension/**'
      - '!apps/extension/**/*.md'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.20

    - name: Install dependencies
      run: bun install

    - name: Type check
      run: bun run check-types

    - name: Lint
      run: bun run lint

    - name: Build and package extension
      run: |
        bun run build
        cd apps/extension && bun run package

    - name: Verify build output
      run: |
        if [ ! -f "apps/extension/build/chrome-mv3-prod.zip" ]; then
          echo "Error: Extension package not found!"
          exit 1
        fi
        echo "Extension package size: $(ls -lh apps/extension/build/chrome-mv3-prod.zip | awk '{print $5}')"

    - name: Get extension version and commit info
      id: get_info
      run: |
        VERSION=$(node -p "require('./apps/extension/package.json').version")
        COMMIT_MSG=$(git log -1 --pretty=format:"%s")
        COMMIT_SHA=$(git rev-parse --short HEAD)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
        echo "Extension version: $VERSION"
        echo "Commit: $COMMIT_SHA"
        echo "commit_msg<<EOF" >> $GITHUB_OUTPUT
        echo "$COMMIT_MSG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Prepare release artifact
      run: |
        cp apps/extension/build/chrome-mv3-prod.zip TalkToMyTabs-v${{ steps.get_info.outputs.version }}.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_info.outputs.version }}
        name: TalkToMyTabs Extension v${{ steps.get_info.outputs.version }}
        body: |
          ## TalkToMyTabs Chrome Extension v${{ steps.get_info.outputs.version }}

          **Build:** ${{ steps.get_info.outputs.commit_sha }}

          **Changes:**
          ${{ steps.get_info.outputs.commit_msg }}

          ### 📦 Installation Instructions:
          1. Download the `TalkToMyTabs-v${{ steps.get_info.outputs.version }}.zip` file below
          2. Extract the ZIP file to a folder
          3. Open Chrome and go to `chrome://extensions/`
          4. Enable "Developer mode" in the top right
          5. Click "Load unpacked" and select the extracted folder
          6. The extension should now be installed and ready to use!

          ### ✨ Features:
          - AI chat sidebar (Ctrl+Shift+Y)
          - Article simplifier popup (Ctrl+Shift+P)
          - New tab dashboard with article feed
          - Context menu integration

          ### ⚠️ Note:
          This is an unpacked extension for development/testing. For production use, 
          please wait for the Chrome Web Store release.

          ---
          *Built automatically from commit ${{ steps.get_info.outputs.commit_sha }}*
        files: |
          TalkToMyTabs-v${{ steps.get_info.outputs.version }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}